### ISSUE TITLE
please look me

### ISSUE THREAD

**Issue by hppp123** [StevenAZy/PyConvU-Net#1]
woule u tell me this question?thank u very much
RuntimeError: running_mean should contain 512 elements not 128

**Comment by StevenAZy** [comment]
Maybe you need to modify the dimension of output.
If it can not work, you can give me the specific line of code that encounters the problem.
Thank you for your issue!

**Comment by hppp123** [comment]
Thanks for your reply! I just copied your source code to make this error. Since I haven't fully understood your code (just copied), I would like to know where this should be modified

**Comment by StevenAZy** [comment]
> Thanks for your reply! I just copied your source code to make this error. Since I haven't fully understood your code (just copied), I would like to know where this should be modified

Can you provide complete error information including which line of error occurred？

**Comment by hppp123** [comment]
Warning: module PyConv4 is treated as a zero-op.
Warning: module PyConvBlock is treated as a zero-op.
Warning: module DoublePyConv is treated as a zero-op.
Warning: module PyConvUnet is treated as a zero-op.
Traceback (most recent call last):
  File "main.py", line 299, in <module>
    macs, params = get_model_complexity_info(model,(3,512,512),as_strings=True,print_per_layer_stat=True,verbose=True)
  File "/home/chen/桌面/hp/code/PyConvU-Net-master/flops_counter.py", line 42, in get_model_complexity_info
    _ = flops_model(batch)
  File "/home/chen/anaconda3/envs/hp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/chen/桌面/hp/code/PyConvU-Net-master/PyconvUnet.py", line 233, in forward
    c1 = self.conv1(x)
  File "/home/chen/anaconda3/envs/hp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/chen/桌面/hp/code/PyConvU-Net-master/PyconvUnet.py", line 173, in forward
    return self.pyconv(input)
  File "/home/chen/anaconda3/envs/hp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/chen/anaconda3/envs/hp/lib/python3.6/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/chen/anaconda3/envs/hp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/chen/anaconda3/envs/hp/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 140, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/home/chen/anaconda3/envs/hp/lib/python3.6/site-packages/torch/nn/functional.py", line 2150, in batch_norm
    input, weight, bias, running_mean, running_var, training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: running_mean should contain 512 elements not 128

**Comment by StevenAZy** [comment]
> return self.pyconv(input)

![image](https://user-images.githubusercontent.com/22978326/134802057-30a244b9-a320-42ab-956d-6beb4462f6f6.png)
You can try change 512 to 218 in main.py!

**Comment by hppp123** [comment]
Do both parameters need to be modified? 218?
it is the same error.

**Comment by StevenAZy** [comment]
> Do both parameters need to be modified? 218?
> it is the same error.

Yes

**Comment by StevenAZy** [comment]
> Do both parameters need to be modified? 218?
> it is the same error.

Yes, 128

**Comment by hppp123** [comment]
it is also the same error！

**Comment by StevenAZy** [comment]
What is the dimension of your input？

**Comment by hppp123** [comment]
dataset？

**Comment by hppp123** [comment]
it is lungkaggkedataset

**Comment by hppp123** [comment]
512×512

**Comment by hppp123** [comment]
512×512

**Comment by hppp123** [comment]
class PyConvUnet(nn.Module):

    def __init__(self, in_ch, out_ch):
        super(PyConvUnet, self).__init__()
        self.conv1 = DoublePyConv(in_ch, 32*4)
        # self.pyconv1 = PyConvBlock(32,8,pyconv_kernels=[3,5],pyconv_groups=[1,4])
        self.pool1 = nn.MaxPool2d(2)
        self.conv2 = DoublePyConv(32*4, 64*4)
        # self.pyconv2 = PyConvBlock(64, 16,pyconv_kernels=[3,5],pyconv_groups=[1,4])
        self.pool2 = nn.MaxPool2d(2)
        self.conv3 = DoublePyConv(64*4, 128*4)
        # self.pyconv3 = PyConvBlock(128,32,pyconv_kernels=[3,5],pyconv_groups=[1,4])
        self.pool3 = nn.MaxPool2d(2)
        self.conv4 = DoublePyConv(128*4, 256*4)
        # self.pyconv4 = PyConvBlock(256,64,pyconv_kernels=[3,5],pyconv_groups=[1,4])
        self.pool4 = nn.MaxPool2d(2)
        self.conv5 = DoublePyConv(256*4, 512*4)
        self.pool5 = nn.MaxPool2d(2)
你这段代码注释掉的是不需要的吗

**Comment by Byronnar** [comment]
> woule u tell me this question?thank u very much RuntimeError: running_mean should contain 512 elements not 128

请问您这边解决这个问题了么，希望能回复一下，谢谢！

**Comment by Byronnar** [comment]
@hppp123 @StevenAZy
